apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-seba
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-seba
    app.kubernetes.io/part-of: integ-app-mkll
  name: hacbs-test-project-seba
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-seba
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-seba
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/nbe-e2e-cpot-tenant/integ-app-mkll/hacbs-test-project-seba@sha256:cccc3223818343e5e09ed2f42785e1806aac738a5806d5fca34b5c356b14b012
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
